### ISSUE TITLE
Documentation master task list

### ISSUE THREAD

**Issue by m-renaud** [tibbe/unordered-containers#191]
- [ ] Improve Data.HashMap (Strict and Lazy) module docs
- [ ] Improve Data.HashSet module docs
- [ ] Add example invocations for Data.HashMap functions
- [ ] Add example invocations for Data.HashSet functions
- [ ] Write beginner friendly introduction for unordered-containers
- [ ] Document all necessary class instances
